Layers doc
lucat1/visimp pull request #64
Opened 2024-01-05 22:10 UTC by foxyseta

2024-02-05 17:43 UTC, lucat1 approved these changes
Didn't read, but I trust @foxyseta

2024-02-05 17:46 UTC, lucat1 requested changes

2024-02-05 17:46 UTC, lucat1 commented on lua/visimp/layers/diagnostics.lua
> +local toggle = require('trouble').toggle
You can't require outside the package this layer depends upon outside of the`load` function, as this code can be loaded before the package is even installed.

To fix this, you should add this require both on line 8 (in the make_toggle function) and in the `L.load` function.

Also, much for the same reason, I'd advise against binding inside the `preload` if the binds depend on the dependency being installed..

2024-02-06 01:13 UTC, foxyseta commented on lua/visimp/layers/diagnostics.lua
> +local toggle = require('trouble').toggle
[06eb7d2](https://github.com/lucat1/visimp/pull/64/commits/06eb7d244a36ccfaca57ec63033c76a79b72f6c6)

2024-02-06 08:36 UTC, lucat1 approved these changes

2024-02-06 08:48 UTC, merged